Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'app/controllers/**'
    - 'app/helpers/**'
    - 'app/jobs/**'
    - 'app/models/**'
    - 'spec/features/**'
    - 'spec/models/**'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - '**/Gemfile'
    - 'Rakefile'
  UseCache: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
